name = "aI_Calculations"
uuid = "8d3019d5-8f01-4003-8102-deb2283bc4eb"
authors = ["John Ferrier"]
version = "0.1.0"

[deps]


[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
[targets]
test = ["Test","SafeTestsets"]
